# Generated by Django 5.2 on 2025-05-14 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('bidpreformat', models.AutoField(primary_key=True, serialize=False)),
                ('bid', models.CharField(db_default=models.Value("LPAD(bidpreformat::text, 4, '0')", output_field=models.CharField()), max_length=4, unique=True)),
                ('bname', models.CharField(blank=True, max_length=20, null=True)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'boards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('picidpreformat', models.AutoField(primary_key=True, serialize=False)),
                ('picid', models.CharField(db_default=models.Value("LPAD(picidpreformat::text, 4, '0')", output_field=models.CharField()), max_length=4, unique=True)),
                ('pic', models.BinaryField()),
                ('regtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pictures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uidpreformat', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(db_default=models.Value("LPAD(uidpreformat::text, 4, '0')", output_field=models.CharField()), max_length=4, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('intro', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pins',
            fields=[
                ('pinidpreformat', models.AutoField(primary_key=True, serialize=False)),
                ('pinid', models.CharField(db_default=models.Value("LPAD(pinidpreformat::text, 4, '0')", output_field=models.CharField()), max_length=4, unique=True)),
                ('original', models.BooleanField(blank=True, null=True)),
                ('frdonly', models.BooleanField(blank=True, null=True)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(blank=True, db_column='bid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.boards')),
                ('picid', models.ForeignKey(blank=True, db_column='picid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.pictures')),
            ],
            options={
                'db_table': 'pins',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('sidpreformat', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(db_default=models.Value("LPAD(sidpreformat::text, 4, '0')", output_field=models.CharField()), max_length=4, unique=True)),
                ('sname', models.CharField(blank=True, max_length=20, null=True)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users')),
            ],
            options={
                'db_table': 'streams',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='boards',
            name='uid',
            field=models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users'),
        ),
        migrations.CreateModel(
            name='Picturetags',
            fields=[
                ('pk', models.CompositePrimaryKey('picid', 'tag', blank=True, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=20)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('picid', models.ForeignKey(db_column='picid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.pictures')),
            ],
            options={
                'db_table': 'picturetags',
                'managed': True,
                'unique_together': {('picid', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Streamboards',
            fields=[
                ('pk', models.CompositePrimaryKey('sid', 'bid', blank=True, editable=False, primary_key=True, serialize=False)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.boards')),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.streams', to_field='sid')),
            ],
            options={
                'db_table': 'streamboards',
                'managed': True,
                'unique_together': {('sid', 'bid')},
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('pk', models.CompositePrimaryKey('uid', 'pinid', blank=True, editable=False, primary_key=True, serialize=False)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('pinid', models.ForeignKey(db_column='pinid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.pins')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users')),
            ],
            options={
                'db_table': 'likes',
                'managed': True,
                'unique_together': {('uid', 'pinid')},
            },
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('pk', models.CompositePrimaryKey('uidfr', 'uidto', 'regtime', blank=True, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('regtime', models.DateTimeField()),
                ('uidfr', models.ForeignKey(db_column='uidfr', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users')),
                ('uidto', models.ForeignKey(db_column='uidto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitations_uidto_set', to='pinterest.users')),
            ],
            options={
                'db_table': 'invitations',
                'managed': True,
                'unique_together': {('uidfr', 'uidto', 'regtime')},
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('pk', models.CompositePrimaryKey('uid1', 'uid2', blank=True, editable=False, primary_key=True, serialize=False)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('uid1', models.ForeignKey(db_column='uid1', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users')),
                ('uid2', models.ForeignKey(db_column='uid2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='friends_uid2_set', to='pinterest.users')),
            ],
            options={
                'db_table': 'friends',
                'managed': True,
                'unique_together': {('uid1', 'uid2')},
            },
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('pk', models.CompositePrimaryKey('uid', 'bid', blank=True, editable=False, primary_key=True, serialize=False)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.boards')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users')),
            ],
            options={
                'db_table': 'follows',
                'managed': True,
                'unique_together': {('uid', 'bid')},
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('pk', models.CompositePrimaryKey('uid', 'pinid', 'regtime', blank=True, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('regtime', models.DateTimeField()),
                ('pinid', models.ForeignKey(db_column='pinid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.pins')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users')),
            ],
            options={
                'db_table': 'comments',
                'managed': True,
                'unique_together': {('uid', 'pinid', 'regtime')},
            },
        ),
    ]
