# Generated by Django 5.2.7 on 2025-11-15 00:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('picid', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('regtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pictures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('intro', models.CharField(blank=True, max_length=500, null=True)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(blank=True, max_length=20, null=True)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('frdonly', models.BooleanField(blank=True, null=True)),
                ('uid', models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pins',
            fields=[
                ('pinid', models.AutoField(primary_key=True, serialize=False)),
                ('original', models.BooleanField(blank=True, null=True)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(blank=True, db_column='bid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.boards')),
                ('picid', models.ForeignKey(blank=True, db_column='picid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.pictures')),
            ],
            options={
                'db_table': 'pins',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pintags',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=50)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('pinid', models.ForeignKey(db_column='pinid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.pins')),
            ],
            options={
                'db_table': 'pintags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=20, null=True)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'streams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('pk', models.CompositePrimaryKey('uid', 'bid', blank=True, editable=False, primary_key=True, serialize=False)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.boards')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follows',
                'managed': True,
                'unique_together': {('uid', 'bid')},
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('pk', models.CompositePrimaryKey('uid1', 'uid2', blank=True, editable=False, primary_key=True, serialize=False)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('uid1', models.ForeignKey(db_column='uid1', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('uid2', models.ForeignKey(db_column='uid2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='friends_uid2_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friends',
                'managed': True,
                'unique_together': {('uid1', 'uid2')},
            },
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('pk', models.CompositePrimaryKey('uidfr', 'uidto', 'regtime', blank=True, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('regtime', models.DateTimeField()),
                ('uidfr', models.ForeignKey(db_column='uidfr', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('uidto', models.ForeignKey(db_column='uidto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitations_uidto_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitations',
                'managed': True,
                'unique_together': {('uidfr', 'uidto', 'regtime')},
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('pk', models.CompositePrimaryKey('uid', 'pinid', blank=True, editable=False, primary_key=True, serialize=False)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('pinid', models.ForeignKey(db_column='pinid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.pins')),
            ],
            options={
                'db_table': 'likes',
                'managed': True,
                'unique_together': {('uid', 'pinid')},
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('pk', models.CompositePrimaryKey('uid', 'pinid', 'regtime', blank=True, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('regtime', models.DateTimeField()),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('pinid', models.ForeignKey(db_column='pinid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.pins')),
            ],
            options={
                'db_table': 'comments',
                'managed': True,
                'unique_together': {('uid', 'pinid', 'regtime')},
            },
        ),
        migrations.CreateModel(
            name='Streamboards',
            fields=[
                ('pk', models.CompositePrimaryKey('sid', 'bid', blank=True, editable=False, primary_key=True, serialize=False)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.boards')),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.streams')),
            ],
            options={
                'db_table': 'streamboards',
                'managed': True,
                'unique_together': {('sid', 'bid')},
            },
        ),
    ]
