# Generated by Django 5.2 on 2025-05-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Users',
            name='intro',
            field=models.CharField(max_length=500, blank=True, null=True),
        ),
    ]