# Generated by Django 5.2 on 2025-05-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0002_add_intro'),
        ('pinterest', '0003_add_creq'),
    ]

    operations = [
    ]
