# Generated by Django 5.2.7 on 2025-11-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0003_remove_users_id_users_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='frdonly',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
