# Generated by Django 5.2.1 on 2025-05-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0004_merge_0002_add_intro_0003_add_creq'),
    ]

    operations = [
        migrations.AddField(
            model_name='pins',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
