# Generated by Django 5.2.1 on 2025-05-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0005_pins_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pins',
            name='frdonly',
        ),
        migrations.RemoveField(
            model_name='pins',
            name='image',
        ),
        migrations.AddField(
            model_name='boards',
            name='frdonly',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
