# Generated by Django 5.2.1 on 2025-05-18 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0006_remove_pins_frdonly_remove_pins_image_boards_frdonly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='creq',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.CreateModel(
            name='Pintags',
            fields=[
                ('tidpreformat', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=50)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('pinid', models.ForeignKey(db_column='pinid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.pins', to_field='pinid')),
            ],
            options={
                'db_table': 'pintags',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Picturetags',
        ),
    ]
