# Generated by Django 5.2.1 on 2025-05-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='picid',
            field=models.ForeignKey(blank=True, db_column='picid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.pictures', to_field='picid'),
        ),
    ]
