# Generated by Django 5.2.1 on 2025-05-18 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0002_alter_pins_picid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pins',
            name='bid',
            field=models.ForeignKey(blank=True, db_column='bid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.boards', to_field='bid'),
        ),
    ]
