# Generated by Django 5.2.1 on 2025-05-18 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0003_alter_pins_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='uid',
            field=models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='uid1',
            field=models.ForeignKey(db_column='uid1', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='uid2',
            field=models.ForeignKey(db_column='uid2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='friends_uid2_set', to='pinterest.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='uidfr',
            field=models.ForeignKey(db_column='uidfr', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='uidto',
            field=models.ForeignKey(db_column='uidto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitations_uidto_set', to='pinterest.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.users', to_field='uid'),
        ),
    ]
