# Generated by Django 5.2.1 on 2025-05-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0005_alter_users_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
