# Generated by Django 5.2.1 on 2025-05-18 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0006_alter_users_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintags',
            name='tid',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='boards',
            name='bid',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='pinid',
            field=models.ForeignKey(db_column='pinid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.pins', to_field='pinid'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.boards', to_field='bid'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='pinid',
            field=models.ForeignKey(db_column='pinid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.pins', to_field='pinid'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picid',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pins',
            name='pinid',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='streamboards',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='pinterest.boards', to_field='bid'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='sid',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
