# Generated by Django 5.2.1 on 2025-05-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0007_pintags_tid_alter_boards_bid_alter_comments_pinid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pintags',
            name='tid',
        ),
    ]
