# Generated by Django 5.2.1 on 2025-05-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0008_remove_pintags_tid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pintags',
            old_name='tidpreformat',
            new_name='tid',
        ),
    ]
