# Generated by Django 5.2.1 on 2025-05-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0009_rename_tidpreformat_pintags_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='bid',
            field=models.CharField(db_default=models.Value("LPAD(bidpreformat::text, 4, '0')", output_field=models.CharField()), max_length=4, unique=True),
        ),
    ]
