# Generated by Django 5.2.1 on 2025-05-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0010_alter_boards_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.CharField(db_default=models.Value("LPAD(uidpreformat::text, 4, '0')", output_field=models.CharField()), max_length=4, unique=True),
        ),
    ]
