# Generated by Django 5.2.1 on 2025-05-18 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0011_alter_users_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='bid',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='boards',
            name='regtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
